// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *Oubliette) DeepCopyInto(out *Oubliette) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *Oubliette) DeepCopy() *Oubliette {
	if in == nil {
		return nil
	}
	out := new(Oubliette)
	in.DeepCopyInto(out)
	return out
}

func (in *Oubliette) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *OublietteList) DeepCopyInto(out *OublietteList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]Oubliette, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *OublietteList) DeepCopy() *OublietteList {
	if in == nil {
		return nil
	}
	out := new(OublietteList)
	in.DeepCopyInto(out)
	return out
}

func (in *OublietteList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *OublietteSpec) DeepCopyInto(out *OublietteSpec) { *out = *in }

func (in *OublietteStatus) DeepCopyInto(out *OublietteStatus) {
	*out = *in
	if in.ForgottenAt != nil {
		out.ForgottenAt = in.ForgottenAt.DeepCopy()
	}
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		copy(out.Conditions, in.Conditions)
	}
}
